

<!-- Footer -->
<footer class="container-fluid page-footer font-small pb-1 fixed-bottom">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3" >

    <!-- Adresse -->
    <span><strong>Adresse: </strong>Cupcakevej 9, 2800 Lyngby &bull;

    <!-- Telefon -->
    <strong>Telefon: </strong><a href="tel:12-34-56">12-34-56</a> &bull;

    <!-- Email -->
    <strong>Email:</strong> <a href="mailto:mums@cupcake.com">mums@cupcake.com</a> &bull;
    </span>
    <span>
    &copy; 2020 All rights reserved:
      <a href="#"> Cupcakegruppen.com</a>
      </span>
    </div>
    <!-- Copyright -->

 </footer>
<!-- Footer -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>